### ISSUE TITLE
Dynamically create catalog entries

### ISSUE THREAD

**Issue by roumail** [quantumblacklabs/kedro#138]
## Description
I have two python dictionaries that I'm saving locally using kedro.io.PickleLocalDataSet. 

These dictionaries are created using the snippet below:
```
import pickle
import pandas as pd

df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},
                   index=['falcon', 'dog', 'spider', 'fish'])

d1 = {
    'name' : df.sample(2) ,
    'phone' : df.sample(2),
    }
d2 = {"hello" : df}

with open("d1", "wb") as h:
    pickle.dump(d1, h)

with open("d2", "wb") as h:
    pickle.dump(d2, h)

```
Therefore, my catalog.yml looks like this :
```
d1:
  type: kedro.io.PickleLocalDataSet
  filepath: ./d1

d2:
  type: kedro.io.PickleLocalDataSet
  filepath: ./d2
```

I wish there were an easy way to "explode" the two dictionaries, d1 and d2, into CSVLocalDatasets:

```
name:
  type: kedro.io.CSVLocalDataSet
  filepath: ./name.csv

phone:
  type: kedro.io.CSVLocalDataSet
  filepath: ./phone.csv

hello:
  type: kedro.io.CSVLocalDataSet
  filepath: ./hello.csv

```

I first tried to do this by creating a node that would read a dictionary and output a list of dataframes using a small function like the following:

```
def dict2df_list(d):
  return [v for k,v in d.items()]
```

However I get stuck when trying to specify the config.yml for the above node because I don't know how many dataframes will be generated up front. As seen in the example, d1 has two dataframes as values and d2 has only one dataframe. 

It should be clear already but I've been using the YAML file based way of declaring pipelines/nodes/config etc. I understand that using code API is equivalent but I'm not as familiar using that approach to declare pipelines etc. 

## Context
There are many times when we have a node that creates a list of outputs. We can't always pre-specify how many outputs will be generated. Therefore, some documentation around such use cases would be really helpful. 
I'm not exactly sure how to proceed here.

## Possible Alternatives
When I encountered a similar situation in the past, I resolved the dilemma by implementing a separate node for each case of the twenty cases I had. Without a looping construct, ofcourse there was a lot of code duplication but at least it worked. I cannot use a similar approach in this case since I don't know the total number of cases up front.
