### ISSUE TITLE
Question-Bug-docs CSVGCSDataSet failed not sure the credentials format. Bug?

### ISSUE THREAD

**Issue by centraal-g** [quantumblacklabs/kedro#224]
First of all, I want to thanks to the team behind this project/tool, we strongly believe that the principles behind ´kedro´ are very useful to increase the quality of the data-products.

In advance my apologies if this is not the channel for this kind of inquiries. But I'm not 100% sure if the issue is a question, bug or if  is related with GCS documentation in progress to be updated.

## What are you trying to do?
`kedro==0.15.5`
We are trying to load a csv file from GCS. We have defined in the kedro project the following information in the configuration files:

`catalog.yml`
```
udr_history:
  type: kedro.contrib.io.gcs.CSVGCSDataSet
  filepath: "gs://path/to/file.csv"
  credentials: gcp_labo
```

`credentials.yml`
```
gcp_labo:
    client_id: "id"
    client_secret: "secret"
    refresh_token: "XXX"
    type: "authorized_user"
```
the data in `credentials.yml` is an exactly copy of the information in `~/.config/gcloud/application_default_credentials.json`.

when we test (using for example `kedro ipython`), the `context` and `catalog` variables are created properly. However when we try to load the dataset (`context.catalog.load("udr_history")`):

1. This message is printed: ´YYYY-MM-DD HH:MM:SS - kedro.io.data_catalog - INFO - Loading data from `udr_history` (CSVGCSDataSet)´
2. After some seconds, the following error appears:
`DataSetError: Failed while loading data from data set CSVGCSDataSet(filepath=path/to/file.csv).
('invalid_scope: Bad Request', '{\n  "error": "invalid_scope",\n  "error_description": "Bad Request"\n}')`

in [JSONGCSDataSet doc](https://kedro.readthedocs.io/en/latest/kedro.contrib.io.gcs.JSONGCSDataSet.html#kedro.contrib.io.gcs.JSONGCSDataSet) is mentioned others parameters that are more similar of the parameters that are generated in the  keys for **Service Accounts**  but are not the same (`client_email`, `token_uri`, `refresh_token` (**not generated in the service accounts keys**), `client_secret`, `client_id`).

Can anyone guide us to make `kedro` reads the CSV file in the GCS?

Thanks in advance.

**Comment by DmitriiDeriabinQB** [comment]
@centraal-g Kedro relies on `gcsfs.GCSFileSystem` to communicate with the Google Cloud Storage, and the error that you've posted is likely to be a permission error. `GCSFileSystem` uses `full_control` scope by default, which may not be claimed by your credentials.

Could you please make sure that your credentials allow full control to the bucket or alternatively modify your catalog entry as follows:
```yaml
udr_history:
  type: kedro.contrib.io.gcs.CSVGCSDataSet
  filepath: "gs://path/to/file.csv"
  credentials: gcp_labo
  gcsfs_args:
    access: read_only
```
