### ISSUE TITLE
[KED-1358] conda install kedro

### ISSUE THREAD

**Issue by marcusinthesky** [quantumblacklabs/kedro#313]
## Description
Anaconda is a popular package manager for many data scientists cause of its ability to resolve non-python dependencies, like Cuda.  Many tools like MLFLOW rely heavily on anaconda in order to ensure compatibility when serving model on Databricks or Azure.  

## Context
Many pypi packages can be automatically compiled to be install as conda packages using `conda skeleton python kedro`, `conda convert --platform all /path/to/package/` and `conda upload `path/to/package/`.  For kedro this fails, as the pypi .tar.gz does not have the test_requirements.txt. 

I have made a workaround by building specifically from the GitHub repo, which I have made [availible](https://anaconda.org/marcusgawronsky/kedro). 

## Possible Implementation
Change what is uploaded to pypi to ensure the test_requirements.txt is uploaded.  

## Possible Alternatives
meta.yml
```
{% set name = "kedro" %}
{% set version = "0.15.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 0.15.8
  git_url: https://github.com/quantumblacklabs/kedro.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - kedro

about:
  home: "https://kedro.readthedocs.io/"
  license: "BSD"
  license_family: "APACHE"
  license_file: "LICENSE.md"
  summary: "A Python library that implements software engineering best-practice for data and ML pipelines."
  doc_url: "https://kedro.readthedocs.io/"
  dev_url: "https://github.com/quantumblacklabs/kedro/tree/develop"
```
