### ISSUE TITLE
[KED-1582] Support parameter objects with typed attributes to simplify configuration management

### ISSUE THREAD

**Issue by JonathanLofgrenQB** [quantumblacklabs/kedro#328]
## Description
In big Kedro projects with hundreds of nodes the number of parameters can also grow quite large. We tend to group the parameters under top level keys in the conf yaml's to avoid having to supply too many inputs to the nodes in form of separate `"params:.."` and to get some form of logical grouping. So we might do something like:
```yaml
# parameters.yml (or in separate files in a directory conf/base/parameters/)

training:
  num_iter: 100
  learning_rate: 0.01
  # ...and potentially many more :)
```
and then add `"params:training"` as an input to our modelling node.

The problem now becomes managing these sets of parameters, which are just passed into the nodes as dictionaries. Example of pain points we have experienced related to this:
- No IDE help to avoid making silly mistakes like accessing invalid keys in the dictionaries, also no auto-complete.
- Unclear approach for providing documentation on meaning and required types for the parameters. Should this be in the form of comments in the YAML or in the docstring in the given node?
- The tests are required to construct these parameter dictionaries which can be cumbersome, given the lack of default values. (Could potentially load the yml files in the tests but this coupling doesn't seem very nice.)

Therefore I am suggesting Kedro to support optionally allowing the user to provide a typed schema for sets of parameters, in which case Kedro can pass in an object with attributes instead of a dictionary.

## Context
This could simplify the management of large sets of parameters, and reduce mistakes made. I am keen to hear if others share the pain of this, hence I am posting the issue here.

## Possible Implementation
I am suggesting to use [pydantic](https://pydantic-docs.helpmanual.io/) for this, which is a python library for data validation and settings management. It's used in other projects such as FastAPI, Ludwig and gluon-ts to name a few.

From the users perspective it could look something like this:

```yaml
# tell Kedro which specification to use for the training parameters
training__type_spec: example_project.nodes.ds.modelling.TrainingParams
training:
  num_iter: 100
  learning_rate: 0.01
```

```python
# src/example_project/nodes/ds/modelling.py

from pydantic import BaseModel
...

class TrainingParams(BaseModel):
    """ <bunch of nice docstring explaining the parameters> """
    num_iter: int # required value
    learning_rate: float = 0.01 # optional value: has default

def train_model(
    train_x: pd.DataFrame, train_y: pd.DataFrame, params: TrainingParams
) -> np.ndarray:
    # Note the TrainingParams type hint so that our IDE gives
    # us auto complete, type checking etc.
    ...
    model.fit(..., num_iter=params.num_iter, learning_rate=params.learning_rate)
    return model
```

`TrainingParams`  provides a place to document the different parameters, and also provide default values in which case it gets simple to construct these parameters objects in our unit tests. We get a bunch of other cool feature from pydantic to help manage the parameters like custom validation rules, recursive pydantic models,  type checking etc.

I have a simple implementation working, by just overriding the attribute `.params` in the context object and adding some code to convert the dictionaries to pydantic models. I am happy to work on it more if there is interest.

I am keen to hear if others are interested in this or have any thoughts.

Thanks,
Jonathan
