### ISSUE TITLE
[KED-1619] catalog.yaml configuration reference

### ISSUE THREAD

**Issue by fkromer** [quantumblacklabs/kedro#344]
I'd like to understand what valid entries in `catalog.yaml` files are. Searching the kedro docs got me to [The Data Catalog](https://kedro.readthedocs.io/en/latest/04_user_guide/04_data_catalog.html). However the docs is an example, not really a reference. I was looking for something like e.g. [GitLab's `.gitlab-ci.yml` configuration reference](https://docs.gitlab.com/ee/ci/yaml/README.html).

**Comment by 921kiyo** [comment]
Hi, @fkromer thank you for your question. 
Here is the list of datasets you can register in `catalog.yml` as type. jhttps://kedro.readthedocs.io/en/latest/kedro.extras.datasets.html

But if you have any specific question, feel free to ask us here or StackOverflow with kedro tag.  

I can see the information is a bit scattered in the docs. We will have a look at Github docs and improve the structure of the docs.

**Comment by fkromer** [comment]
Hi @921kiyo , thanks for the hint. I was interested in what keys such as `type`, etc. for different `file_format`s are valid as well. E.g. https://github.com/quantumblacklabs/kedro-examples/blob/master/kedro-exercises/spaceflight/conf/base/catalog.yml :

```
weather:
  type: spark.SparkDataSet
  filepath: s3a://your_bucket/data/01_raw/weather*
  file_format: csv
  credentials: dev_s3
  load_args:
    header: True
    inferSchema: True
  save_args:
    sep: '|'
    header: True

scooters:
  type: pandas.SQLTableDataSet
  credentials: scooters_credentials
  table_name: scooters
  load_args:
    index_col: ['name']
    columns: ['name', 'gear']
  save_args:
    if_exists: 'replace'
    # if_exists: 'fail'
    # if_exists: 'append'
```
