### ISSUE TITLE
Save kedro pipeline image by pillow.ImageDataSet without manually launching kedro-viz server

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#375]
## Description
Currently we have to launch the `kedro-viz` server to see the visualized pipeline. 
It will be more convenient if we can save the pipeline image by simply setting in `catalog.yml` like this:

```yaml
_PIPELINE_IMAGE:
  type: pillow.ImageDataSet
  filepath: data/_pipeline_image.png
```

## Context
This issue is related to #56 (moved to https://github.com/quantumblacklabs/kedro-viz/issues/31), but perhaps a more convenient feature.

## Possible Implementation
Provide some of the visualization code in `kedro-viz` as a Kedro hook.

## Possible Alternatives
Port some of the visualization code in `kedro-viz` to KedroContext.
