### ISSUE TITLE
How to work with long-lived refresh tokens and short-lived access tokens?

### ISSUE THREAD

**Issue by f-istvan** [quantumblacklabs/kedro#386]
## Description
In my scenario I have a service that works with short-lived access tokens and long-lived refresh tokens. So I need to use the long-lived refresh token to get a short-lived token. Than I can get the data with the short-lived token. When short-lived expires I need to get a new one. 

I saw this example in the docs where I can pass arbitrary number of parameters to the underlying library (requests):

```
us_corn_yield_data:
  type: api.APIDataSet
  url: https://quickstats.nass.usda.gov
  params:
    key: SOME_TOKEN
    format: JSON
    commodity_desc: CORN
    statisticcat_des: YIELD
    agg_level_desc: STATE
    year: 2000
```

But in this case the `SOME_TOKEN` is the short-lived token for getting the data from the API. But what I want is to check if the short-lived token is still valid and if not request a new one with the long-lived token.

The question is: Is there a built-in support for such a use case in `api.APIDataSet` or in any other kedro Datasets?

Thank you!
