### ISSUE TITLE
Data Catalog dynamic arguments from non-local source

### ISSUE THREAD

**Issue by vonTrappG** [quantumblacklabs/kedro#387]
A node in my pipeline pulls raw data from a given data source, however, the data source pull requires a dynamic input argument (e.g. an API token that expires, or a 'last-pulled' date that is updated in a remote database each time data are pulled). The dynamic input parameter values are not stored locally and need to be pulled each time the pipeline is run. In the case of a token, via an API request for new token, or in the case of the SQL query, the last date pulled which is stored in a database table that is not on the local machine executing the pipeline.

Example catalog entry:

```
awesome_sql_query:
  type: pandas.SQLQueryDataSet
  credentials: secret_credentials
  sql: SELECT * FROM awesome_table WHERE dates >= last_date AND dates < current_date   
  load_args:
    last_date: date_sql_db_data_was_last_pulled
    current_date: date_of_current_sql_db_pull
```

My question is: What is the best practice for implementing a service for fetching dynamic input parameters (in this example: last_date and current_date) required for pulling data from a data source?

Thanks! Enjoying Kedro so far!
