### ISSUE TITLE
[KED-1748] Namespace Exclusions for Modular Pipelines

### ISSUE THREAD

**Issue by benhorsburgh** [quantumblacklabs/kedro#404]
## Description

When I use the `namespace` feature with global catalog entries, I have to add confusing `input` and `output` arguments to keep the catalog entries global.

For example, let's say I have the following cleaning pipeline

```python
# inside module `cleaning`
def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=do_cleaning,
                inputs={
                    "data": "input_data",
                    "params": "params:cleaning",
                    "data_dict": "data_dict",
                },
                outputs={"data": "output_data"},
                name="clean",
            )
        ]
    )
```

I can use this as a modular pipeline using the new `pipeline` helper:

```python
clean_pipeline = pipeline(pipe=clean.create_pipeline(), namespace="clean")
```

This modular pipeline expects the following catalog entries:

```yaml
clean.input_data:
  type: MemoryDataSet
clean.data_dict:
  type: MemoryDataSet
clean.output_data:
  type: MemoryDataSet
```

If I want to re-use this pipeline for different datasets, it's super easy, I just namespace it:

```python
my_dataset_clean_pipeline = pipeline(pipe=clean_pipeline, namespace="my_dataset")
```

which now expects the following catalog entries:

```yaml
my_dataset.clean.input_data:
  type: MemoryDataSet
my_dataset.clean.data_dict:
  type: MemoryDataSet
my_dataset.clean.output_data:
  type: MemoryDataSet
```

However, let's say that `data_dict` is global, and both `clean_pipeline` and `my_dataset_clean_pipeline` should both use this global dataset, instead of the namespaced one. I can currently achieve this as:

```python
clean_pipeline = pipeline(
    pipe=clean.create_pipeline(),
    inputs={"data_dict": "data_dict"},
    namespace="clean"
)

my_dataset_clean_pipeline = pipeline(
    pipe=clean_pipeline,
    inputs={"data_dict": "data_dict"},
    namespace="my_dataset"
)
```

What is really annoying here, especially with several datasets, I can only exclude them from namespacing by explicitly mapping them back onto themselves (`"data_dict": "data_dict"`).

## Context

This is important because it is common to use global reference datasets, for example dictionaries or ontologies. Whilst there is a work around, the code is not semantically meaningful, and is not intuitive to people not familiar with the work around.

## Possible Implementation

A possible implementation could be to add a namespace_excludes argument to `pipeline`. For example:

```python
clean_pipeline = pipeline(
    pipe=clean.create_pipeline(),
    namespace="clean",
    namespace_excludes=["data_dict"]
)
```

## Possible Alternatives

A possible alternative could be to allow catalog referencing, where one dataset name soft-links to another dataset.

For example:

```yaml
data_dict:
  type: MemoryDataSet
clean.data_dict:
  type: ReferenceDataSet
  reference: data_dict
my_dataset.clean.data_dict:
  type: ReferenceDataSet
  reference: data_dict
```
