### ISSUE TITLE
Add json as a parameter to APIDataSet to easily create json requests

### ISSUE THREAD

**Issue by dataengineerone** [quantumblacklabs/kedro#424]
## Description
Using the APIDataSet is great, but things get a little complicated if one wants to POST a JSON object.
The only way one can POST a json object is if they do the following.

1. Manually add `Content-Type: application/json` to the `headers`.
2. Manually stringify an object into json.

This results in a `catalog.yml` that looks something like this:

```yaml
api_example:
  type: api.APIDataSet
  url: https://jsonplaceholder.typicode.com/posts
  method: 'POST'
  headers:
    Content-Type: application/json
  data: '{"hi": "there", "bye": "bear"}'
```

## Context

The `requests.request` object that APIDataSet wraps Does support `json` as an argument, which would automatically stringify the python dictionary object for us, as well as change the header.

The result is that the previous `catalog.yml` entry would be much simpler to create, looking like:

```yaml
api_example:
  type: api.APIDataSet
  url: https://jsonplaceholder.typicode.com/posts
  method: 'POST'
  json:
    hi: there
    bye: bear
```

JSON is the lingua franca of HTTP requests, so having it more readily available in our APIDataSet I think is useful.
