### ISSUE TITLE
Remove quotation marks (Part 1)

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#460]
## Description

- We've had many authors of our documentation and this is sometimes reflected in stylistic differences
- We want to move everything to the same style
- For this exercise, you need to remove quotation marks from code that is documented [here](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/05_data/02_kedro_io.md#partitioned-dataset-definition)

## Actual Result

Here's what the entry country looks like: 
```
my_partitioned_dataset:
  type: "PartitionedDataSet"
  path: "s3://my-bucket-name/path/to/folder"  # path to the location of partitions
  dataset: "pandas.CSVDataSet"  # shorthand notation for the dataset which will handle individual partitions
  credentials: "my_credentials"
  load_args:
    load_arg1: "value1"
    load_arg2: "value2"
```

## Expected Result

Here's what we'd like it to look like:
```
my_partitioned_dataset:
  type: PartitionedDataSet
  path: s3://my-bucket-name/path/to/folder  # path to the location of partitions
  dataset: pandas.CSVDataSet  # shorthand notation for the dataset which will handle individual partitions
  credentials: my_credentials
  load_args:
    load_arg1: value1
    load_arg2: value2
```
