### ISSUE TITLE
Remove quotation marks (Part 2)

### ISSUE THREAD

**Issue by yetudada** [quantumblacklabs/kedro#461]
## Description

- We've had many authors of our documentation and this is sometimes reflected in stylistic differences
- We want to move everything to the same style
- For this exercise, you need to remove quotation marks from code that is documented [here](https://github.com/quantumblacklabs/kedro/blob/master/docs/source/05_data/02_kedro_io.md#partitioned-dataset-definition), you need to scroll down the page to find it in this section #460 covers working on the first code block

## Actual Result

Here's what the entry country looks like: 
```
# conf/base/catalog.yml

my_partitioned_dataset:
  type: "PartitionedDataSet"
  path: "s3://my-bucket-name/path/to/folder"
  dataset:  # full dataset config notation
    type: "pandas.CSVDataSet"
    load_args:
      delimiter: ","
    save_args:
      index: false
  credentials: "my_credentials"
  load_args:
    load_arg1: "value1"
    load_arg2: "value2"
  filepath_arg: "filepath"  # the argument of the dataset to pass the filepath to
  filename_suffix: ".csv"
```

## Expected Result

Here's what we'd like it to look like, note that if the entry has some sort of punctuation then the quotation marks remain:
```
# conf/base/catalog.yml

my_partitioned_dataset:
  type: PartitionedDataSet
  path: s3://my-bucket-name/path/to/folder
  dataset:  # full dataset config notation
    type: pandas.CSVDataSet
    load_args:
      delimiter: ","
    save_args:
      index: false
  credentials: my_credentials
  load_args:
    load_arg1: value1
    load_arg2: value2
  filepath_arg: filepath  # the argument of the dataset to pass the filepath to
  filename_suffix: ".csv"
```

**Comment by s-mawjee** [comment]
I'll work on this

**Comment by s-mawjee** [comment]
Should this change include the following or not?
```yaml
my_partitioned_dataset:
  type: IncrementalDataSet
  path: s3://my-bucket-name/path/to/folder
  dataset: pandas.CSVDataSet
  checkpoint: "2020-01-01/data.csv"
```
