### ISSUE TITLE
[KED-1966] dask.ParquetDataSet conversion failure

### ISSUE THREAD

**Issue by CarvalhoGyn** [quantumblacklabs/kedro#471]
## Description
I've been trying to insert a .parquet file into ADLS using dask.ParquetDataSet, and I have received a conversion error. But running the Dask command directly through Jupyter works normally on the same file.

## Context
It is not possible to insert .parquet file into ADLS through dask.ParquetDataSet.
### Using Dask directly
``` python
ddf = dd.from_pandas(df, npartitions=2)
ddf.to_parquet(
    path="abfs://dass-restroalimentacao/culturas.parquet",
    compression='snappy',
    engine='pyarrow',
    storage_options={
        'account_name': NAME,
        'account_key': KEY
    }
)
```

### Catalog
``` yaml
culturas_adls:
  type: dask.ParquetDataSet
  filepath: abfs://dass-restroalimentacao/culturas.parquet
  credentials: adls
  save_args:
    compression: snappy
    engine: pyarrow
```

## Log
```bat
kedro.io.core.DataSetError: Failed while saving data to data set ParquetDataSet(filepath=abfs://dass-restroalimentacao/culturas.parquet.snappy, save_args={'compression': snappy, 'engine': pyarrow, 'write_index': False}).
('Could not convert 17118c14-1c94-4794-904b-9842192d8dad with type UUID: did not recognize Python value type when inferring an Arrow data type', 'Conversion failed for column MaterialColheitaId with type object')
```

## Environment

* Kedro version used (0.16.4):
* Python version used (3.7.7):
* Operating system and version: OSX
