### ISSUE TITLE
CSV dataset extra newline

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#492]
## Description
The kedro save csv with extra "/n", as a result when view in Excel, it looks like this,
![image](https://user-images.githubusercontent.com/18221871/91132927-e73f4400-e6df-11ea-9d32-93d512d75a4c.png)

The fix is to add the argument manually
```
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv
  save_args:
    line_terminator: "\n"
```

## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [And so on...]

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.4
* Python version used (`python -V`): python: 3.7.5
* Operating system and version: Window 10

**Comment by MerelTheisenQB** [comment]
Hi @noklam, can you provide steps for how to reproduce this issue?

**Comment by noklam** [comment]
@MerelTheisenQB  Sorry for late, I have been struggling how to create the dataset with this bug.
catalog.yml
```yaml
sample:
  type: pandas.CSVDataSet
  filepath: data2/sample.csv
```
python script to create and load dataset
```python
df['test'] = ['123']
df['test'] = '\x9d'

df.to_csv('sample.csv') # to data/sample.csv
pd.read_csv('sample.csv') # success
catalog.load('sample') # UnicodeDecodeError: 'charmap'
```
d=catalog.load('2_all_invoice_note_after_2020')

**Comment by noklam** [comment]
I would assume the default behaviour is same as pd.read_csv(), but apparently something is weird here.

**Comment by noklam** [comment]
@MerelTheisenQB 

# Steps to reproduce
1. kedro new csv_bug
2. for all prompt repsonse, type Y
3. edit "catalog.yml" to following
```
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv


example_train_x:
  type: pandas.CSVDataSet
  filepath: data/05_model_input/output.csv
```
4. kedro run
5. 
![image](https://user-images.githubusercontent.com/18221871/91520841-e3eac900-e928-11ea-941d-e1d0e9dc080a.png)



(edited: deleted previous wrong comments)
