### ISSUE TITLE
Load data from intermediate after processing?

### ISSUE THREAD

**Issue by jmrichardson** [quantumblacklabs/kedro#517]
Hi, I am new to Kedro and have been looking through the documentation and can't find a reference for automatically loading the intermediate (already processed dataset) vs processing each time I run a pipeline.  In other words, I would like to pre process a file, save to intermediate location:

```
kibot_minute_ibm:
  type: pandas.CSVDataSet
  filepath: data/01_raw/kibot/minute/ibm.csv

X_trn:
  type: pickle.PickleDataSet
  filepath: data/02_intermediate/X_trn.pkl

X_tst:
  type: pickle.PickleDataSet
  filepath: data/02_intermediate/X_tst.pkl
```

The above does that, but the next time I run "kedro run" it does the whole pipeline again even though the original source data file hasn't changed.  Is there a way to enable caching when node hasn't changed and the data itself hasn't changed?
