### ISSUE TITLE
Kedro with minio

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#530]
## What are you trying to do?
Kedro support major cloud storage API. I would like to use self-host storage instead, I am thinking to use Minio (S3 Compatible API)
Does kedro support this?

https://min.io/

**Comment by 921kiyo** [comment]
Kedro uses `fsspec` and `s3fs` to handle IO to cloud storage. Looks like [s3fs supports minio](https://s3fs.readthedocs.io/en/latest/#self-hosted-s3), so you could pass it as an argument of `fs_args` in a dataset class. See [how to specify it in catalog](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#data-catalog-args-parameters) Hope this helps :)

**Comment by noklam** [comment]
@921kiyo  
The configuration is a bit trickier, maybe this could be added to kedro documentations. To use `s3fs`, we have to use a filepath `filepath :s3://path` and an extra `endpoint_url` client kwargs.

```yaml
test:
  type: pandas.CSVDataSet
  filepath: s3://kedro-test/test.csv
  credentials: dev_s3
```

for `credentials.yml`,  a typical s3 credentials look like this
```yaml
dev_s3:
  aws_access_key_id: token
  aws_secret_access_key: key
```
If we need to use **Minio**
We will configure like this instead.
```yaml
dev_s3:
  key: key
  secret: secret:
  cleitn_kwargs:
    endpoint_url : 'http://localhost:9000' # default for minio
```
