### ISSUE TITLE
Update SQL dataset instead of create a new

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#545]
## What are you trying to do?
I want to update a certain table with Kedro, which require 
1. Delete some rows base on some condition
2. Insert new rows

Trials:
1. Use Kedro DataCatalog API
```
table:
  type: pandas.SQLQueryDataSet
  sql: delete * from table where x=1
  credentials: oracle
```
Failed: Kedro DataCatalog API seems does not let you just delete, it expects rows return.

2. Use plain pd.read_sql(), I cannot find a way to access to the credentials.yml
