### ISSUE TITLE
[KED-2639] Cannot read csv in chunks with pandas

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#598]
## Description
Cannot read csv in chunks with kedro data catalog.

df = pd.read_csv(csv, chunksize=1000)
df.get_chunk()

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
```yaml
train_dataset:
  type: pandas.CSVDataSet
  filepath: 'mycsv.csv'
  load_args:
    chunksize: 50000
```
df = catalog.load("train_dataset")
df.get_chunk()
> ValueError: I/O operation on closed file.
> df
> <pandas.io.parsers.TextFileReader at 0x7fde97a82450>

## Expected Result
I should be able to loop over the reader.

## Actual Result
ValueError: I/O operation on closed file.
```
-- If you received an error, place it here.

```
> ValueError: I/O operation on closed file.
```
```yaml
train_dataset:
  type: pandas.CSVDataSet
  filepath: 'mycsv.csv'
  load_args:
    chunksize: 50000
```

-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
kedro: 0.16.6
* Python version used (`python -V`):
3.7.5
* Operating system and version:
Ubuntu
