### ISSUE TITLE
spaceflight tutorial: registering xlsx data does not work

### ISSUE THREAD

**Issue by mcbeem** [quantumblacklabs/kedro#644]
## Description
In the spaceflight tutorial, the code for configuring the `catalog.yml` file to read the `shuttles.xlsx` data fails because the [xlrd package can no longer read xlsx files.](https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported)

This fails:
```
shuttles:
  type: pandas.ExcelDataSet
  filepath: data/01_raw/shuttles.xlsx
```

However, this seems to work:

`pip install openpyxl`

Then, add to `catalog.yml`

```
shuttles:
  type: pandas.ExcelDataSet
  filepath: data/01_raw/shuttles.xlsx
  load_args:
    engine: openpyxl
```
