### ISSUE TITLE
Simple lambda x: x node hangs on output

### ISSUE THREAD

**Issue by NathanFarmer** [quantumblacklabs/kedro#679]
## Description
I have a simple node where I am doing a read/write operation from one Oracle database to another. I can load tables from both databases through the catalog in Jupyter Notebook, but I am unable to move data between databases. The table in the save (write) database gets created, but no records are written. I tried reducing the save_args chunksize to 5 to confirm that the connection isn't just very slow, but no records are being written. The table is only about 5,000 records total.

## Steps to Reproduce
1. Catalog
```
apps.source_table:
  type: pandas.SQLQueryDataSet
  sql: 'SELECT * FROM apps.source_table'
  credentials: oracledb1
  load_args:
    index_col: source_table_id
    parse_dates: ['date1, 'date2']

destination_table:
  type: pandas.SQLTableDataSet
  table_name: destination_table
  credentials: oracledb2
  save_args:
    if_exists: append
    chunksize: 5
```
2. Create pipeline
```
Pipeline([
      node(
          lambda x: x,
          inputs='apps.source_table',
          outputs='destination_table',
      ),
])
```
3. ```kedro run```

## Expected Result
I expect the pipeline to finish running the node in a matter of minutes and for a copy of the source table to appear in the destination database.

## Actual Result
The pipeline hangs on the save step and an empty table has been created in the save (write) database.

```
2021-01-26 23:40:34,114 - kedro.io.data_catalog - INFO - Loading data from `apps.source_table` (SQLQueryDataSet)...
2021-01-26 23:40:37,733 - kedro.pipeline.node - INFO - Running node: <lambda>([apps.source_table]) -> [destination_table]
2021-01-26 23:40:37,733 - kedro.io.data_catalog - INFO - Saving data to `destination_table` (SQLTableDataSet)...
```

## Your Environment
I am reading using SQLQueryDataSet because the source table is actually a synonym, not an actual table object.

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.17.0
* Python version used (`python -V`): Python 3.8.6
* Operating system and version: macOS Catalina 10.15.7
