### ISSUE TITLE
Nested parameters update via command line / config file

### ISSUE THREAD

**Issue by noklam** [quantumblacklabs/kedro#750]
## Description
Currently, when passing a parameter to override configurations like
`kedro run --params key:value`, it only supports top-level key but not nested dictionary. This is not flexible for experiments.

Similarly, `kedro run --config=config.yml`, overwriting via config file suffers from the same top-level key only problem.

Ideally.
```
# paramters.yml
group1:
   key1: 1
   key2: 2
   key3: 3
```
Ideally, this should be the expected result

```
# paramters.yml
group1:
   key1: 1
   key2: 2
   key3: 4
```

Current behavior

```
# paramters.yml
group1:
   key3: 4
```

Related #605

## Context
A lot of parameters are organized in groups instead of being a top-level key.

## Possible Implementation
Maybe a simple nest dict update is enough, I am not sure 

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.
