### ISSUE TITLE
[KED-2667] Pycharm Kedro Catalog Schema error.

### ISSUE THREAD

**Issue by ElCuboNegro** [quantumblacklabs/kedro#771]
Schema validation: Incompatible types.
Required: object. Actual: string.

## Context
I'm in the first steps after finish the configuration of the Schema for the Kedro Catalog in Pycharm 2021.1.1.

## Steps to Reproduce
1. having a valid file in the `./conf/local/credentials.yml`
2. having a `catalog.yml` with code like:
    ```yaml
  addresses:
    type: pandas.SQLTableDataSet
    table_name: addresses
    credentials: rdsEnjoy
    layer: raw
    ```

## Expected Result
the rdsEnjoy should not be picked as an incompatible type

## Actual Result
the `rdsEnjoy` resalts as an error with `Schema validation: Incompatible types. Required: object. Actual: string.`

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:
