### ISSUE TITLE
pandas.CSVDataSet cannot write utf8 chars to a file

### ISSUE THREAD

**Issue by jan-kaufmann** [quantumblacklabs/kedro#772]
## Description
I am working with pandas.CSVDataSet files that contain text. When these DataFrames contain non-ascii character such as 'less-than-or-equal' : \u2264 kedro throws an exception upon writing the file to disk. 

The problem seems to be limited to windows.

## Steps to Reproduce
1. Define a simple csv file on windows with a non-ascii character
```
column1,column2,column3
a,b,c
≤,2,3
```

2. Try to load and write that file in catalog.yml
```
test_read_file:
  type: pandas.CSVDataSet
  filepath: data/01_raw/t.csv
  load_args:
    encoding: utf8

test_write_file:
  type: pandas.CSVDataSet
  filepath: data/01_raw/t2.csv
  save_args:
    encoding: utf8
```

3. Define a simple node
```
def t_node(df):
    print(df)
    df.to_csv("this_works.csv", encoding="utf8") 
    return df

node(
func = t_node,
inputs = "test_read_file",
outputs = "test_write_file",
name = "t_node",
)
```

## Expected Result
The returned data frame should be written to t2.csv. 

## Actual Result
The plain pandas to_csv writes the file successful to disk. 
But kedro raises an exception:

> Failed while saving data to data set CSVDataSet(filepath=C:/Users/[user]/Documents/kedro/health_ai/data/01_raw/t2.csv, load_args={}, protocol=file, save_args={'encoding': utf8, 'index': False}).
'charmap' codec can't encode character '\u2264' in position 0: character maps to <undefined>

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Windows 10
*  Kedro 0.17.3
* Python 3.8.10
* Pandas 1.2.4
