### ISSUE TITLE
Set ssl and sslverifcation to catalog or db credentials

### ISSUE THREAD

**Issue by Soufraz** [quantumblacklabs/kedro#801]
## Description
Connect into a trino/presto db using catalog and credential file.
In datagrip and dbeaver I can connect only with two params:
SSL=True
SSLVerification=NONE
I am trying to find out how to fill this params in catalog definition or credentials file.
When I add to con url the pipeline not even start to run.

## Context
Id like to get data using catalogs through trino/presto. I installed sqlalchemy-trino and change the con url to trino://
But to connect in database I need to set ssl params even in datagrip or dbeaver.
Then I am trying to find out how to pass this params in credentials con.
I tried ssl, ssl_context, ssl_verification and a few more but any param that I add I get an error of not recognized params.

```
kedro.io.core.DataSetError: Failed while loading data from data set SQLQueryDataSet(load_args={}, sql=BIG_QUERY_HERE.
HTTPSConnectionPool(host='presto.address.com', port=8446): Max retries exceeded with url: /v1/statement (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f183810d520>, 'Connection to presto.address.com timed out. (connect timeout=30.0)'))
```

## Your Environment
sqlalchemy==1.4.15
sqlalchemy-trino==0.3.0
psycopg2-binary

* Kedro version used: 0.17.3
* Python version used: 3.8.5
* Operating system and version: Manjaro 21

**Comment by MerelTheisenQB** [comment]
Hi @Soufraz, thanks for reaching out!
Could you paste the catalog entry you tried?

**Comment by Soufraz** [comment]
```
trino_connection:
  con: trino://user:pass@presto.address.com:8446/hive

attachments:
  type: pandas.SQLQueryDataSet
  credentials: trino_connection
  sql: 'query here'
```

Params Ive tried:
```
load_args:
  ssl:
    fake_flag_to_enable_tls: True
    verification: None
```
